# Generated by Django 5.1.7 on 2026-04-10 16:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0002_organization_parent_organization"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="hacienda_branch_code",
            field=models.CharField(
                default="001",
                max_length=3,
                validators=[
                    django.core.validators.RegexValidator(
                        "^\\d{3}$", "Debe contener exactamente 3 dígitos."
                    )
                ],
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="hacienda_terminal_code",
            field=models.CharField(
                default="00001",
                max_length=5,
                validators=[
                    django.core.validators.RegexValidator(
                        "^\\d{5}$", "Debe contener exactamente 5 dígitos."
                    )
                ],
            ),
        ),
        migrations.AddConstraint(
            model_name="organization",
            constraint=models.UniqueConstraint(
                fields=("hacienda_branch_code", "hacienda_terminal_code"),
                name="uq_org_hacienda_branch_terminal",
            ),
        ),
    ]
