# Generated by Django 5.1.7 on 2026-04-21 03:50

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_organization_hacienda_branch_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaaSModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=140)),
                ('group', models.CharField(choices=[('base', 'Base'), ('operations', 'Operación'), ('growth', 'Crecimiento'), ('finance', 'Finanzas'), ('premium', 'Premium')], default='base', max_length=20)),
                ('description', models.TextField(blank=True, default='')),
                ('route_hint', models.CharField(blank=True, default='', max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('is_public', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['group', 'sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SaaSPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=140)),
                ('description', models.TextField(blank=True, default='')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('monthly_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('annual_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('recommended_billing_cycle', models.CharField(choices=[('monthly', 'Mensual'), ('annual', 'Anual')], default='monthly', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.AlterModelOptions(
            name='subscription',
            options={'ordering': ['organization__name']},
        ),
        migrations.AddField(
            model_name='subscription',
            name='base_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='subscription',
            name='billing_cycle',
            field=models.CharField(choices=[('monthly', 'Mensual'), ('annual', 'Anual'), ('custom', 'Personalizado')], default='monthly', max_length=20),
        ),
        migrations.AddField(
            model_name='subscription',
            name='next_billing_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='subscription',
            name='status',
            field=models.CharField(choices=[('trial', 'Prueba'), ('active', 'Activa'), ('past_due', 'Pendiente de pago'), ('suspended', 'Suspendida'), ('cancelled', 'Cancelada')], default='trial', max_length=20),
        ),
        migrations.AddField(
            model_name='subscription',
            name='trial_ends_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='organization',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='tenants.organization'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='plan_catalog',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscriptions', to='tenants.saasplan'),
        ),
        migrations.CreateModel(
            name='SaaSPlanModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_included', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_plans', to='tenants.saasmodule')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_modules', to='tenants.saasplan')),
            ],
            options={
                'ordering': ['plan_id', 'sort_order', 'module__name'],
            },
        ),
        migrations.AddField(
            model_name='saasplan',
            name='modules',
            field=models.ManyToManyField(related_name='plans', through='tenants.SaaSPlanModule', to='tenants.saasmodule'),
        ),
        migrations.CreateModel(
            name='SubscriptionModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=True)),
                ('source', models.CharField(choices=[('plan', 'Plan'), ('addon', 'Add-on'), ('custom', 'Personalizado')], default='plan', max_length=20)),
                ('activated_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_links', to='tenants.saasmodule')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_modules', to='tenants.subscription')),
            ],
            options={
                'ordering': ['subscription_id', 'module__group', 'module__sort_order', 'module__name'],
            },
        ),
        migrations.CreateModel(
            name='OrganizationFeatureFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField()),
                ('label', models.CharField(max_length=140)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('is_enabled', models.BooleanField(default=False)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_flags', to='tenants.organization')),
                ('module', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feature_flags', to='tenants.saasmodule')),
            ],
            options={
                'ordering': ['organization_id', 'key'],
                'constraints': [models.UniqueConstraint(fields=('organization', 'key'), name='uq_org_feature_flag')],
            },
        ),
        migrations.AddConstraint(
            model_name='saasplanmodule',
            constraint=models.UniqueConstraint(fields=('plan', 'module'), name='uq_plan_module'),
        ),
        migrations.AddConstraint(
            model_name='subscriptionmodule',
            constraint=models.UniqueConstraint(fields=('subscription', 'module'), name='uq_subscription_module'),
        ),
    ]
