# Generated by Django 5.1.7 on 2026-04-09 20:35

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("customers", "0001_initial"),
        ("tenants", "0002_organization_parent_organization"),
    ]

    operations = [
        migrations.CreateModel(
            name="LoyaltyMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("member_code", models.CharField(max_length=40)),
                ("enrolled_at", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Activo"),
                            ("suspended", "Suspendido"),
                            ("inactive", "Inactivo"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("lifetime_points", models.PositiveIntegerField(default=0)),
                ("available_points", models.IntegerField(default=0)),
                ("reserved_points", models.PositiveIntegerField(default=0)),
                ("last_activity_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="loyalty_memberships",
                        to="customers.customer",
                    ),
                ),
            ],
            options={
                "ordering": ["program_id", "-enrolled_at"],
            },
        ),
        migrations.CreateModel(
            name="LoyaltyProgram",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.SlugField(max_length=40)),
                ("name", models.CharField(max_length=160)),
                ("description", models.TextField(blank=True)),
                ("points_name", models.CharField(default="Puntos", max_length=40)),
                ("is_active", models.BooleanField(default=True)),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="loyalty_programs",
                        to="tenants.organization",
                    ),
                ),
            ],
            options={
                "ordering": ["organization_id", "name"],
            },
        ),
        migrations.CreateModel(
            name="LoyaltyPointEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "entry_type",
                    models.CharField(
                        choices=[
                            ("earn", "Acumulación"),
                            ("redeem", "Canje"),
                            ("adjustment", "Ajuste"),
                            ("expiration", "Expiración"),
                            ("reservation", "Reserva"),
                            ("release", "Liberación"),
                        ],
                        max_length=20,
                    ),
                ),
                ("points", models.IntegerField()),
                ("source_reference", models.CharField(blank=True, max_length=120)),
                ("source_metadata", models.JSONField(blank=True, default=dict)),
                ("event_at", models.DateTimeField()),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="point_entries",
                        to="loyalty.loyaltymember",
                    ),
                ),
                (
                    "program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="point_entries",
                        to="loyalty.loyaltyprogram",
                    ),
                ),
            ],
            options={
                "ordering": ["-event_at", "-id"],
            },
        ),
        migrations.AddField(
            model_name="loyaltymember",
            name="program",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="members",
                to="loyalty.loyaltyprogram",
            ),
        ),
        migrations.CreateModel(
            name="LoyaltyReward",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.SlugField(max_length=40)),
                ("name", models.CharField(max_length=140)),
                ("description", models.TextField(blank=True)),
                ("points_cost", models.PositiveIntegerField()),
                ("stock", models.PositiveIntegerField(default=0)),
                ("is_unlimited_stock", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("starts_at", models.DateTimeField(blank=True, null=True)),
                ("ends_at", models.DateTimeField(blank=True, null=True)),
                (
                    "program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rewards",
                        to="loyalty.loyaltyprogram",
                    ),
                ),
            ],
            options={
                "ordering": ["program_id", "name"],
            },
        ),
        migrations.CreateModel(
            name="LoyaltyRedemption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField(default=1)),
                ("points_spent", models.PositiveIntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Borrador"),
                            ("confirmed", "Confirmado"),
                            ("cancelled", "Cancelado"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("external_reference", models.CharField(blank=True, max_length=120)),
                ("notes", models.TextField(blank=True)),
                ("requested_at", models.DateTimeField(auto_now_add=True)),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="redemptions",
                        to="loyalty.loyaltymember",
                    ),
                ),
                (
                    "point_entry",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="redemption",
                        to="loyalty.loyaltypointentry",
                    ),
                ),
                (
                    "program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="redemptions",
                        to="loyalty.loyaltyprogram",
                    ),
                ),
                (
                    "reward",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="redemptions",
                        to="loyalty.loyaltyreward",
                    ),
                ),
            ],
            options={
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="LoyaltyRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rule_type",
                    models.CharField(
                        choices=[
                            ("earn", "Acumulación"),
                            ("redeem", "Canje"),
                            ("expiration", "Expiración"),
                        ],
                        max_length=20,
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("description", models.TextField(blank=True)),
                (
                    "points_per_currency_unit",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=10, null=True
                    ),
                ),
                (
                    "currency_per_point",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=10, null=True
                    ),
                ),
                (
                    "minimum_purchase_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                ("minimum_points_to_redeem", models.PositiveIntegerField(default=0)),
                (
                    "points_expire_in_days",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("starts_at", models.DateTimeField(blank=True, null=True)),
                ("ends_at", models.DateTimeField(blank=True, null=True)),
                (
                    "program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rules",
                        to="loyalty.loyaltyprogram",
                    ),
                ),
            ],
            options={
                "ordering": ["program_id", "rule_type", "id"],
            },
        ),
        migrations.AddField(
            model_name="loyaltypointentry",
            name="related_rule",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="point_entries",
                to="loyalty.loyaltyrule",
            ),
        ),
        migrations.CreateModel(
            name="LoyaltyTier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.SlugField(max_length=40)),
                ("name", models.CharField(max_length=80)),
                ("rank", models.PositiveSmallIntegerField()),
                ("min_lifetime_points", models.PositiveIntegerField(default=0)),
                (
                    "multiplier",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("1.00"),
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                ("benefits", models.TextField(blank=True)),
                (
                    "program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tiers",
                        to="loyalty.loyaltyprogram",
                    ),
                ),
            ],
            options={
                "ordering": ["program_id", "rank"],
            },
        ),
        migrations.AddField(
            model_name="loyaltymember",
            name="tier",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="members",
                to="loyalty.loyaltytier",
            ),
        ),
        migrations.AddIndex(
            model_name="loyaltyprogram",
            index=models.Index(
                fields=["organization", "is_active"], name="idx_lp_org_active"
            ),
        ),
        migrations.AddConstraint(
            model_name="loyaltyprogram",
            constraint=models.UniqueConstraint(
                fields=("organization", "code"), name="uq_loyalty_program_org_code"
            ),
        ),
        migrations.AddConstraint(
            model_name="loyaltyprogram",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("end_date__isnull", True),
                    ("start_date__isnull", True),
                    ("end_date__gte", models.F("start_date")),
                    _connector="OR",
                ),
                name="ck_loyalty_program_dates",
            ),
        ),
        migrations.AddIndex(
            model_name="loyaltyreward",
            index=models.Index(
                fields=["program", "is_active"], name="idx_lrw_program_active"
            ),
        ),
        migrations.AddConstraint(
            model_name="loyaltyreward",
            constraint=models.UniqueConstraint(
                fields=("program", "code"), name="uq_loyalty_reward_program_code"
            ),
        ),
        migrations.AddConstraint(
            model_name="loyaltyreward",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("ends_at__isnull", True),
                    ("starts_at__isnull", True),
                    ("ends_at__gte", models.F("starts_at")),
                    _connector="OR",
                ),
                name="ck_loyalty_reward_dates",
            ),
        ),
        migrations.AddIndex(
            model_name="loyaltyredemption",
            index=models.Index(
                fields=["program", "status", "requested_at"],
                name="idx_lr_program_status",
            ),
        ),
        migrations.AddIndex(
            model_name="loyaltyredemption",
            index=models.Index(
                fields=["member", "requested_at"], name="idx_lr_member_date"
            ),
        ),
        migrations.AddIndex(
            model_name="loyaltyrule",
            index=models.Index(
                fields=["program", "rule_type", "is_active"],
                name="idx_lrule_program_type",
            ),
        ),
        migrations.AddConstraint(
            model_name="loyaltyrule",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("ends_at__isnull", True),
                    ("starts_at__isnull", True),
                    ("ends_at__gte", models.F("starts_at")),
                    _connector="OR",
                ),
                name="ck_loyalty_rule_dates",
            ),
        ),
        migrations.AddIndex(
            model_name="loyaltypointentry",
            index=models.Index(
                fields=["member", "event_at"], name="idx_lpe_member_event"
            ),
        ),
        migrations.AddIndex(
            model_name="loyaltypointentry",
            index=models.Index(
                fields=["program", "entry_type", "event_at"],
                name="idx_lpe_program_type",
            ),
        ),
        migrations.AddIndex(
            model_name="loyaltypointentry",
            index=models.Index(fields=["expires_at"], name="idx_lpe_expiry"),
        ),
        migrations.AddConstraint(
            model_name="loyaltytier",
            constraint=models.UniqueConstraint(
                fields=("program", "code"), name="uq_loyalty_tier_program_code"
            ),
        ),
        migrations.AddConstraint(
            model_name="loyaltytier",
            constraint=models.UniqueConstraint(
                fields=("program", "rank"), name="uq_loyalty_tier_program_rank"
            ),
        ),
        migrations.AddConstraint(
            model_name="loyaltytier",
            constraint=models.CheckConstraint(
                condition=models.Q(("multiplier__gte", Decimal("0.01"))),
                name="ck_loyalty_tier_multiplier_positive",
            ),
        ),
        migrations.AddIndex(
            model_name="loyaltymember",
            index=models.Index(
                fields=["program", "status"], name="idx_lm_program_status"
            ),
        ),
        migrations.AddIndex(
            model_name="loyaltymember",
            index=models.Index(fields=["customer"], name="idx_lm_customer"),
        ),
        migrations.AddConstraint(
            model_name="loyaltymember",
            constraint=models.UniqueConstraint(
                fields=("program", "customer"),
                name="uq_loyalty_member_program_customer",
            ),
        ),
        migrations.AddConstraint(
            model_name="loyaltymember",
            constraint=models.UniqueConstraint(
                fields=("program", "member_code"), name="uq_loyalty_member_program_code"
            ),
        ),
        migrations.AddConstraint(
            model_name="loyaltymember",
            constraint=models.CheckConstraint(
                condition=models.Q(("lifetime_points__gte", 0)),
                name="ck_loyalty_member_lifetime_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="loyaltymember",
            constraint=models.CheckConstraint(
                condition=models.Q(("reserved_points__gte", 0)),
                name="ck_loyalty_member_reserved_non_negative",
            ),
        ),
    ]
