# Generated by Django 5.1.7 on 2026-04-01 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=120)),
                ('billing_cycle', models.CharField(choices=[('monthly', 'Mensual'), ('yearly', 'Anual')], default='monthly', max_length=20)),
                ('base_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_free', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='SaaSModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrganizationPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tenants.organization')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='platform.plan')),
            ],
        ),
        migrations.CreateModel(
            name='PlanModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('included', models.BooleanField(default=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='platform.plan')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='platform.saasmodule')),
            ],
            options={
                'unique_together': {('plan', 'module')},
            },
        ),
        migrations.CreateModel(
            name='OrganizationModuleAddon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthly_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('active', models.BooleanField(default=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.organization')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='platform.saasmodule')),
            ],
            options={
                'unique_together': {('organization', 'module')},
            },
        ),
    ]
