# Generated by Django 5.1.7 on 2026-04-07 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0003_invoice_tax_regime_installments"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="product_type",
            field=models.CharField(
                choices=[("physical", "Producto"), ("service", "Servicio")],
                default="physical",
                max_length=20,
            ),
        ),
    ]
