# Generated by Django 5.1.7 on 2026-04-10 15:38

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0006_product_service_duration_minutes"),
        ("tenants", "0002_organization_parent_organization"),
    ]

    operations = [
        migrations.CreateModel(
            name="Purchase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("supplier_name", models.CharField(max_length=200)),
                ("supplier_tax_id", models.CharField(max_length=50)),
                ("buyer_name", models.CharField(max_length=200)),
                ("buyer_tax_id", models.CharField(max_length=50)),
                ("issue_date", models.DateField()),
                ("invoice_number", models.CharField(max_length=40)),
                ("numeric_key", models.CharField(max_length=50)),
                (
                    "subtotal",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tenants.organization",
                    ),
                ),
            ],
            options={
                "ordering": ["-issue_date", "-id"],
            },
        ),
        migrations.CreateModel(
            name="PurchaseItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("line_number", models.PositiveIntegerField(default=1)),
                ("description", models.CharField(max_length=220)),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=3,
                        default=Decimal("1.000"),
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.001"))
                        ],
                    ),
                ),
                (
                    "subtotal",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "purchase",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="finance.purchase",
                    ),
                ),
            ],
            options={
                "ordering": ["line_number"],
            },
        ),
        migrations.CreateModel(
            name="TaxQuarterReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.PositiveIntegerField()),
                (
                    "quarter",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(4),
                        ]
                    ),
                ),
                ("economic_activity", models.CharField(max_length=120)),
                (
                    "rts_factor",
                    models.DecimalField(
                        decimal_places=4,
                        max_digits=8,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.0001"))
                        ],
                    ),
                ),
                (
                    "purchases_total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "estimated_tax",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                ("due_date", models.DateField()),
                ("declaration_form", models.CharField(default="D-105", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tenants.organization",
                    ),
                ),
            ],
            options={
                "ordering": ["-year", "-quarter", "-id"],
            },
        ),
        migrations.AddConstraint(
            model_name="purchase",
            constraint=models.UniqueConstraint(
                fields=("organization", "numeric_key"),
                name="uq_purchase_org_numeric_key",
            ),
        ),
        migrations.AddConstraint(
            model_name="taxquarterreport",
            constraint=models.UniqueConstraint(
                fields=("organization", "year", "quarter"), name="uq_tax_quarter_org"
            ),
        ),
    ]
