# Generated by Django 5.1.7 on 2026-04-10 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0001_initial"),
        ("finance", "0006_product_service_duration_minutes"),
        ("tenants", "0002_organization_parent_organization"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="invoice",
            name="uq_invoice_org_number",
        ),
        migrations.AddConstraint(
            model_name="invoice",
            constraint=models.UniqueConstraint(
                fields=("invoice_number",), name="uq_invoice_number"
            ),
        ),
        migrations.AddConstraint(
            model_name="invoice",
            constraint=models.UniqueConstraint(
                fields=("consecutive_number",), name="uq_invoice_consecutive_number"
            ),
        ),
    ]
